import { relative } from 'node:path';
import type { Diagnostic, Location, Model } from '../model.js';

/** A human-readable review document: one section per user, every grant with the code that justifies it. */
export function renderMarkdown(model: Model, rootDir: string): string {
  const rel = (loc: Location): string => `${displayPath(loc.file, rootDir)}:${loc.line}`;
  const lines: string[] = [];
  lines.push(`# NATS permissions`);
  lines.push('');
  lines.push(`Generated by ${model.generator}.`);
  lines.push('');
  if (model.streams.length > 0) {
    lines.push('## Streams');
    lines.push('');
    lines.push('| Stream | Subjects | Source |');
    lines.push('|---|---|---|');
    for (const s of model.streams) lines.push(`| ${s.name} | ${s.subjects.map(code).join(', ')} | ${s.source.startsWith(rootDir) ? relative(rootDir, s.source.split(':')[0]!) + s.source.slice(s.source.split(':')[0]!.length) : s.source} |`);
    lines.push('');
  }
  for (const s of model.services) {
    lines.push(`## ${s.service} (user \`${s.user}\`)`);
    lines.push('');
    const section = (title: string, list: 'publish' | 'subscribe', grants: readonly string[]): void => {
      lines.push(`### ${title}`);
      lines.push('');
      if (grants.length === 0) {
        lines.push('_none_');
        lines.push('');
        return;
      }
      lines.push('| Subject | Because |');
      lines.push('|---|---|');
      for (const g of grants) {
        const prov = s.provenance[`${list} ${g}`] ?? [];
        const because = prov.length === 0 ? 'JetStream account info' : summarize(prov.map((p) => `${p.kind} at ${rel(p.location)}`));
        lines.push(`| ${code(g)} | ${because} |`);
      }
      lines.push('');
    };
    section('Publish', 'publish', s.permissions.publishAllow);
    if (s.permissions.publishDeny.length) lines.push(`Publish deny: ${s.permissions.publishDeny.map(code).join(', ')}`, '');
    section('Subscribe', 'subscribe', s.permissions.subscribeAllow);
    if (s.permissions.subscribeDeny.length) lines.push(`Subscribe deny: ${s.permissions.subscribeDeny.map(code).join(', ')}`, '');
    if (s.permissions.allowResponses) lines.push('May publish to the reply subject of any request it receives (`allow_responses`).', '');
  }
  if (model.diagnostics.length > 0) {
    lines.push('## Diagnostics');
    lines.push('');
    for (const d of model.diagnostics) lines.push(`- ${formatDiagnostic(d, rootDir)}`);
    lines.push('');
  }
  return lines.join('\n');
}

export function displayPath(file: string, rootDir: string): string {
  const rel = relative(rootDir, file);
  return rel && !rel.startsWith('..') ? rel : file;
}

export function formatDiagnostic(d: Diagnostic, rootDir: string): string {
  const where = d.location ? `${displayPath(d.location.file, rootDir)}:${d.location.line}:${d.location.col}: ` : '';
  const service = d.service ? ` [${d.service}]` : '';
  return `${where}${d.severity}${service} ${d.code}: ${d.message}`;
}

function summarize(items: readonly string[]): string {
  const unique = [...new Set(items)];
  if (unique.length <= 3) return unique.join('; ');
  return `${unique.slice(0, 3).join('; ')}; +${unique.length - 3} more`;
}

function code(s: string): string {
  return `\`${s}\``;
}
