import type { Model } from '../model.js';

export interface NscOptions {
  readonly account: string | null;
}

/**
 * An `nsc` script for operator-mode deployments (accounts and users as JWTs).
 * `nsc edit user` is additive, so the script deletes and re-adds each user to
 * make the result equal to the model; run it against a throwaway store first
 * if the users carry other settings you want to keep.
 */
export function renderNsc(model: Model, options: NscOptions): string {
  const account = options.account ?? 'APP';
  const lines: string[] = [];
  lines.push('#!/usr/bin/env bash');
  lines.push(`# Generated by ${model.generator}. Do not edit — run \`natsacl compile --format nsc\`.`);
  lines.push('# Recreates each service user with exactly the permissions the code needs.');
  lines.push('set -euo pipefail');
  lines.push(`ACCOUNT="\${NATSACL_ACCOUNT:-${account}}"`);
  lines.push('');
  for (const s of model.services) {
    const p = s.permissions;
    lines.push(`# ${s.service}`);
    lines.push(`nsc delete user --account "$ACCOUNT" --name ${sq(s.user)} >/dev/null 2>&1 || true`);
    const flags: string[] = [];
    for (const v of p.publishAllow) flags.push(`--allow-pub ${sq(v)}`);
    for (const v of p.subscribeAllow) flags.push(`--allow-sub ${sq(v)}`);
    for (const v of p.publishDeny) flags.push(`--deny-pub ${sq(v)}`);
    for (const v of p.subscribeDeny) flags.push(`--deny-sub ${sq(v)}`);
    if (p.allowResponses) flags.push('--allow-pub-response');
    lines.push(`nsc add user --account "$ACCOUNT" --name ${sq(s.user)} \\`);
    lines.push(flags.map((f) => `  ${f}`).join(' \\\n'));
    lines.push('');
  }
  return lines.join('\n') + '\n';
}

/** Single-quote for bash; subjects never contain quotes but the escape is cheap. */
function sq(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

/** The permissions in NATS JWT vocabulary, per user, for pipelines that mint JWTs themselves. */
export function renderJwtPermissions(model: Model): string {
  const users = model.services.map((s) => ({
    user: s.user,
    service: s.service,
    permissions: {
      pub: { allow: s.permissions.publishAllow, deny: s.permissions.publishDeny },
      sub: { allow: s.permissions.subscribeAllow, deny: s.permissions.subscribeDeny },
      ...(s.permissions.allowResponses ? { resp: { max: 1, ttl: 0 } } : {}),
    },
  }));
  return JSON.stringify({ generator: model.generator, users }, null, 2) + '\n';
}
