import type { Model, ServicePermissions } from '../model.js';

export interface ServerConfOptions {
  readonly account: string | null;
  readonly admin: { readonly user: string; readonly passwordEnv: string } | null;
  readonly passwordEnvOf: (service: string) => string;
}

/**
 * A `nats-server` configuration fragment: one user per service with explicit
 * publish/subscribe allow lists. Passwords are `$ENV` references the server
 * resolves at boot, so no secret is ever in the file. Include it from the main
 * config, or paste the block into it.
 */
export function renderServerConf(model: Model, options: ServerConfOptions): string {
  const lines: string[] = [];
  lines.push(`# Generated by ${model.generator}. Do not edit — run \`natsacl compile\`; CI runs \`natsacl check\`.`);
  lines.push(`# Users: ${model.services.map((s) => s.user).join(', ')}${options.admin ? `, ${options.admin.user} (unrestricted)` : ''}`);
  lines.push('');
  const indent = options.account ? '    ' : '  ';
  if (options.account) {
    lines.push('accounts {');
    lines.push(`  ${options.account} {`);
    lines.push('    jetstream: enabled');
    lines.push('    users: [');
  } else {
    lines.push('authorization {');
    lines.push('  users: [');
  }
  const userIndent = indent + '  ';
  for (const s of model.services) lines.push(...renderUser(s, options.passwordEnvOf(s.service), userIndent));
  if (options.admin) {
    lines.push(`${userIndent}{`);
    lines.push(`${userIndent}  user: "${options.admin.user}"`);
    lines.push(`${userIndent}  password: $${options.admin.passwordEnv}`);
    lines.push(`${userIndent}  # no permissions block: unrestricted, for provisioning streams and operations`);
    lines.push(`${userIndent}}`);
  }
  if (options.account) {
    lines.push('    ]');
    lines.push('  }');
    lines.push('}');
  } else {
    lines.push('  ]');
    lines.push('}');
  }
  return lines.join('\n') + '\n';
}

function renderUser(s: ServicePermissions, passwordEnv: string, indent: string): string[] {
  const p = s.permissions;
  const lines: string[] = [];
  const list = (name: string, values: readonly string[], depth: string): string[] => {
    if (values.length === 0) return [];
    const out = [`${depth}${name}: [`];
    for (const v of values) out.push(`${depth}  ${quote(v)}`);
    out.push(`${depth}]`);
    return out;
  };
  lines.push(`${indent}{`);
  lines.push(`${indent}  user: ${quote(s.user)}`);
  lines.push(`${indent}  password: $${passwordEnv}`);
  lines.push(`${indent}  permissions: {`);
  const pubDepth = `${indent}      `;
  const pub = [...list('allow', p.publishAllow, pubDepth), ...list('deny', p.publishDeny, pubDepth)];
  lines.push(`${indent}    publish: {`);
  lines.push(...(pub.length ? pub : [`${pubDepth}allow: []`]));
  lines.push(`${indent}    }`);
  const sub = [...list('allow', p.subscribeAllow, pubDepth), ...list('deny', p.subscribeDeny, pubDepth)];
  lines.push(`${indent}    subscribe: {`);
  lines.push(...(sub.length ? sub : [`${pubDepth}allow: []`]));
  lines.push(`${indent}    }`);
  if (p.allowResponses) lines.push(`${indent}    allow_responses: true`);
  lines.push(`${indent}  }`);
  lines.push(`${indent}}`);
  return lines;
}

function quote(value: string): string {
  return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}
